### PR TITLE
fix: tashcan li click and ui/ux styling

### PR DESCRIPTION
**Pull request by 4silvertooth**
Hello,
FIX: Right now the whole .trashcan li  is clickable, I have changed it to just the trashcan to be clickable, also the trashcan span is styled such that right now only the trashcan body is clickable and not the cap of trashcan, I have fixed that too. 

UI/UX: aligned the clear and setting button to match the overall margin and padding of the app. Also aligned the trashcan near the row which it belongs to, to make an association. With many items in list its hard to see if that icon belongs to top row or bottom.

### CODE REVIEW

**Comment by GirkovArpa** [comment]
I really like this, but it seems to have broken the feature where you click on an item in history and it moves it to the top of the list:

screenshot

The items are still moved to the top as intended, but their associated trashcan button is deleted and this clashes with all code that relies on the number of `li` elements, like the code which shows the popup error about max contents exceeded.

At line `147` is the code that handles the history item click event, and which has not been revised to be compatible with the changes:

```javascript
event click $(li.item) {
  lastCopiedText = this.text;
  view.clipboard(#put, this.text);

  const textIndex = history.indexOf(this.text);
  const items = $$(li);
  const selfIndex = items.indexOf(this);
  const nextItem = items[selfIndex + 1];
  nextItem.remove();

  $(ul).$prepend(<li .trashcan><span .trashcan-button .material-icons>delete</span></li>);
  $(ul).$prepend(<li .item><span class="clipboard-content">{this.text}</span></li>);

  playSound("success.mp3");

  this.remove();
} 
```

Also I will be honest.  I much prefer the caption to remain in the center of the title bar as it is in the original.  I think this is important for the status of this repo as a clone showcase, since it looks much less like a clone if something as recognizable as the caption is not identical.

**Comment by 4silvertooth** [comment]
Changes according to suggestions.
Also if its clone showcase, try reactor in Sciter, I think you could reduce the lines of code to half, and making it more readable.

**Comment by GirkovArpa** [comment]
Fantastic, thanks again.

I do want to try Reactor next.  But I'll have to try a Hello World first because I've never used React 😄

**Comment by 4silvertooth** [comment]
Well if it helps I haven't used React either till now, but I have a full project in Reactor.

**Pull request merged**
